"""milestone 1 auth

Revision ID: 9f5d54f35d5c
Revises: 4473ef492b59
Create Date: 2026-07-06 08:50:04.581250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5d54f35d5c'
down_revision: Union[str, Sequence[str], None] = '4473ef492b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.alter_column('users', 'github_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'last_login_at',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using='last_login_at::timestamp with time zone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_login_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'github_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
